Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-01, with the labels that each got.

#87 Покращення роботи кнопки, перемикання режимів мапи та дисплею
  src/firmware/firmware.ino
Labels: покращення прошивки

#85 Покращення нічного режиму
  src/firmware/firmware.ino
Labels: покращення прошивки

#98 Додано прогрес оновлення прошивки
  src/firmware/firmware.ino
Labels: покращення прошивки

#99 Додані зображення для режимів мапи
  deploy/svg_generator/svg_generator.py
  src/firmware/firmware.ino
Labels: покращення прошивки

#112 Fix: Запис Lamp RGB лише при зміні значеннь
  src/firmware/firmware.ino
Labels: проблема прошивки, критично

#113 Міграція на HttpUpdate для оновлення прошивок
  src/firmware/firmware.ino
Labels: покращення прошивки

#114 Новий режим: "Хвилина мовчання"
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки

#120 Fix: Виправлення проблеми зі зберіганням змінних
  src/firmware/firmware.ino
Labels: проблема прошивки, критично
