Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-02, with the labels that each got.

#136 Технічне: файли прошивок + тривога в Києві
  src/firmware/firmware.ino
Labels: покращення прошивки

#140 Технічне: виправлення реконнекта wifi
  src/firmware/firmware.ino
Labels: проблема прошивки

#141 Технічне: додано час перезавантаження мапи у випадку відсутності доступу до api-сервера
  src/firmware/firmware.ino
Labels: проблема прошивки

#143 Технічне: правка реконнекта websockets
  src/firmware/firmware.ino
Labels: проблема прошивки, критично

#147 Підтримка I2C сенсорів температури та вологості
  .github/workflows/firmware-compile/action.yml
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки

#148 Fix: Виправлення проблеми з colorPicker у веб-інтерфейсі
  src/firmware/firmware.ino
Labels: проблема прошивки, проблема редактора, критично

#150 Підтримка сенсора освітлення BH1750
  .github/workflows/firmware-compile/action.yml
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки
