Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-08, with the labels that each got.

#212 Технічне: налаштування NTP-сервера
  src/firmware/firmware.ino
Labels: покращення прошивки

#215 Технічне: google stats threading
  deploy/redeploy_websocket_server.sh
  deploy/websocket_server/websocket_server.py
Labels: сервер, технічне

#216 Переїзд на FastLED. Підтримка фонової LED стрічки
  .github/workflows/firmware-compile/action.yml
  src/firmware/firmware.ino
Labels: покращення прошивки

#222 Регулювання гучності динаміка (buzzer)
  .github/workflows/firmware-compile/action.yml
  .gitignore
  libs/ArduinoAsync-master.zip
  libs/ESPAsyncWebServer-3.1.2.zip
  libs/melody-player-2.4.0.zip
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки

#224 Технічне: зовнішня статика
  .gitignore
  deploy/web_server/Dockerfile
  deploy/web_server/jaam_v1.css
  deploy/web_server/jaam_v1.js
  deploy/web_server/web_server.py
Labels: покращення прошивки, сервер, технічне

#225 Додано кнопку налаштування WiFi мережі
  firmware/src/JaamFirmware.cpp
Labels: нова ідея, покращення редактора

#226 Додано підтримку сервісних LED для JAAM 2.0
  firmware/platformio.ini
  firmware/src/JaamFirmware.cpp
Labels: покращення прошивки
