Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-04, with the labels that each got.

#185 Додано відображення вибухів на мапі на основі даних зі ЗМІ
  .github/workflows/clone_count.yml
  .github/workflows/deploy_server.yml
  .github/workflows/deploy_websockets_dev.yml
  deploy/svg_generator/requirements.txt
  deploy/svg_generator/svg_generator.py
  deploy/updater/updater.py
  deploy/web_server/web_server.py
  deploy/websocket_server/websocket_server.py
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки

#187 Оптимізація Dockerfile та реформутування Python коду для легшого сприйняття (повторно до #186)
  .github/workflows/compile.yml
  deploy/alerts/Dockerfile
  deploy/alerts/alerts.py
  deploy/alerts/requirements.txt
  deploy/check/Dockerfile
  deploy/check/check.py
  deploy/check/requirements.txt
  deploy/explosions/Dockerfile
  deploy/explosions/explosions.py
  deploy/explosions/requirements.txt
  deploy/svg_generator/Dockerfile
  deploy/svg_generator/svg_generator.py
  deploy/tcp_server/Dockerfile
  deploy/tcp_server/tcp_server.py
  deploy/update_server/Dockerfile
  deploy/update_server/update_server.py
  deploy/updater/Dockerfile
  deploy/updater/updater.py
  deploy/weather/Dockerfile
  deploy/weather/requirements.txt
  deploy/weather/weather.py
  deploy/web_server/Dockerfile
  deploy/web_server/web_server.py
  deploy/websocket_server/Dockerfile
  deploy/websocket_server/websocket_server.py
Labels: dependencies

#192 Додаткові API по ракетній небезпеці та загрозі безпілотних атак
  deploy/explosions/explosions.py
  deploy/svg_generator/svg_generator.py
  deploy/web_server/web_server.py
Labels: сервер

#193 Технічне: перейменування контейнера, нове АПІ
  .github/workflows/deploy_server.yml
  deploy/etryvoga/Dockerfile
  deploy/etryvoga/etryvoga.py
  deploy/etryvoga/requirements.txt
  deploy/redeploy_etryvoga.sh
  deploy/web_server/web_server.py
Labels: сервер

#195 Підтримка дисплеїв SH1106G та SH1107
  .github/workflows/compile.yml
  .github/workflows/firmware-compile/action.yml
  src/firmware/JaamDisplay.cpp
  src/firmware/JaamDisplay.h
  src/firmware/firmware.ino
Labels: покращення прошивки

#196 Технічне: Винесення логіки роботи сенсорів в окремі файли
  .github/workflows/compile.yml
  .github/workflows/release.yml
  deploy/svg_generator/svg_generator.py
  src/firmware/Definitions.h
  src/firmware/JaamClimateSensor.cpp
  src/firmware/JaamClimateSensor.h
  src/firmware/JaamDisplay.cpp
  src/firmware/JaamDisplay.h
  src/firmware/JaamLightSensor.cpp
  src/firmware/JaamLightSensor.h
  src/firmware/firmware.ino
Labels: покращення прошивки

#197 Технічне: Додано звіт про використання памʼяті
  .github/workflows/compile.yml
  src/firmware/JaamLightSensor.cpp
Labels: технічне

#198 Технічне: Refactoring
  .github/workflows/compile.yml
  .github/workflows/firmware-compile/action.yml
  src/firmware/Constants.h
  src/firmware/JaamClimateSensor.cpp
  src/firmware/JaamClimateSensor.h
  src/firmware/JaamDisplay.cpp
  src/firmware/JaamLightSensor.cpp
  src/firmware/JaamUtils.h
  src/firmware/firmware.ino
Labels: технічне

#199 Технічне: Перенесення функціоналу HA в окремі файли
  .github/workflows/firmware-compile/action.yml
  libs/melody-player-2.4.0.zip
  src/firmware/JaamClimateSensor.cpp
  src/firmware/JaamHomeAssistant.cpp
  src/firmware/JaamHomeAssistant.h
  src/firmware/JaamUtils.h
  src/firmware/firmware.ino
Labels: технічне
