Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-09, with the labels that each got.

#228 Технічне: fix offset in kyiv_distict_mode 4
  deploy/websocket_server/websocket_server.py
  firmware/src/JaamFirmware.cpp
Labels: проблема прошивки, критично

#230 Підтримка додаткової кнопки
  firmware/src/JaamFirmware.cpp
Labels: покращення прошивки

#231 Технічне: окремі сторінки в веб-інтерфейсі
  firmware/src/JaamFirmware.cpp
Labels: покращення редактора, покращення прошивки

#233 Технічне: зміна типу адреси HA mqtt-брокера з IP на універсальну (ip або hostname)
  firmware/src/JaamHomeAssistant.cpp
Labels: покращення прошивки
