Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2024-03, with the labels that each got.

#152 Технічне: Підтримка оновлення SPIFFS розділу
  deploy/update_server/update_server.py
  src/firmware/firmware.ino
Labels: покращення прошивки

#154 Технічне: Оптимізація коду
  .gitignore
  src/firmware/firmware.ino
Labels: покращення прошивки

#156 Технічне: Додана можливість вимикати деякі функції перед збиранням прошивки
  src/firmware/firmware.ino
Labels: покращення прошивки

#157 Додано підтримку динаміка (buzzer)
  .github/workflows/firmware-compile/action.yml
  src/firmware/firmware.ino
Labels: нова ідея, покращення прошивки

#158 Додано регулювання яскравості та інверсію дисплею
  .github/workflows/compile.yml
  .gitignore
  src/firmware/firmware.ino
Labels: нова ідея, покращення редактора, покращення прошивки

#160 Технічне: Покращення збереження налаштувань у вебінтерфейсі
  src/firmware/firmware.ino
Labels: нова ідея, покращення редактора

#161 Технічне: Видалення налаштувань дисплея, якщо він не встановлений
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки

#163 Додано звуки при натисканні на кнопку, кнопку для тестування звуку у вебінтерфейсі
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки

#164 Додано телеметрію у вебінтерфейс
  src/firmware/firmware.ino
Labels: нова ідея, покращення редактора, покращення прошивки

#165 Нові сенсори для HA, додаткові мелодії та інше
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки

#166 Технічне: Оптимізація html
  src/firmware/firmware.ino
Labels: покращення прошивки

#169 Технічне: покращення онлайн-інсталятора
  pages/android-chrome-192x192.png
  pages/android-chrome-512x512.png
  pages/apple-touch-icon.png
  pages/browserconfig.xml
  pages/favicon-16x16.png
  pages/favicon-32x32.png
  pages/favicon.ico
  pages/index.html
  pages/mstile-150x150.png
  pages/site.webmanifest
Labels: flasher

#171 Додано налаштування часового поясу, температуру у домашньому регіоні у телеметрію та HA, додано мелодію "Щедрик"
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки

#173 Опція ігнорування Нічного режиму для звуків при тривозі, інші незначні покращення
  .github/workflows/compile.yml
  .github/workflows/firmware-compile/action.yml
  .github/workflows/upload-pages/action.yml
  flasher/android-chrome-192x192.png
  flasher/android-chrome-512x512.png
  flasher/apple-touch-icon.png
  flasher/bins/jaam.bin
  flasher/bins/jaam.boot.bin
  flasher/bins/jaam.bootloader.bin
  flasher/bins/jaam.partitions.bin
  flasher/bins/jaam_beta.bin
  flasher/bins/jaam_lite.bin
  flasher/browserconfig.xml
  flasher/favicon-16x16.png
  flasher/favicon-32x32.png
  flasher/favicon.ico
  flasher/flag_map.png
  flasher/index.html
  flasher/manifest-beta.json
  flasher/manifest-lite.json
  flasher/manifest.json
  flasher/mstile-150x150.png
  flasher/site.webmanifest
  src/firmware/firmware.ino
Labels: покращення прошивки

#180 Додано анімацію візуального сповіщення про тривоги та відбої
  src/firmware/firmware.ino
Labels: покращення прошивки

#181 Додано режим "Початок на Одещині"
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки

#183 Технічне: Оптимізація коду прошивки
  src/firmware/firmware.ino
Labels: покращення прошивки

#182 Додано перемикач NIght Mode в Home Assistant
  src/firmware/firmware.ino
Labels: покращення редактора, покращення прошивки
