Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2025-01, with the labels that each got.

#271 Fix: Проблеми з декодуванням UTF-8 на веб сервері
  deploy/web_server/web_server.py
  deploy/websocket_server/requirements.txt
  deploy/websocket_server/websocket_server.py
Labels: сервер

#275 Технічне: google logs
  .github/workflows/deploy_websockets.yml
  deploy/redeploy_websocket_server.sh
  deploy/websocket_server/websocket_server.py
Labels: сервер

#274 Покращення роботи кнопок
  firmware/platformio.ini
  firmware/src/JaamButton.cpp
  firmware/src/JaamButton.h
  firmware/src/JaamFirmware.cpp
Labels: покращення прошивки

#280 Збереження/Відновлення налаштувань мапи
  deploy/web_server/jaam_v1.js
  deploy/web_server/jaam_v2.js
  firmware/src/Constants.h
  firmware/src/JaamFirmware.cpp
  updater/src/updater.cpp
Labels: нова ідея, покращення редактора, покращення прошивки

#288 Нові режими для кнопки: Увімк.\Вимк. режим лампи, Зміна яскравості лампи
  firmware/src/Constants.h
  firmware/src/JaamButton.cpp
  firmware/src/JaamButton.h
  firmware/src/JaamFirmware.cpp
Labels: нова ідея, покращення прошивки

#290 Сервер: Watchdog
  .github/workflows/deploy_watchdog.yml
  deploy/redeploy_watchdog.sh
  deploy/watchdog/Dockerfile
  deploy/watchdog/watchdog.sh
  deploy/watchdog_ws.sh
Labels: критично, сервер

#292 Сервер: Повітряні тривоги з районами
  deploy/alerts/alerts.py
  deploy/alerts/requirements.txt
  deploy/etryvoga/requirements.txt
  deploy/svg_generator/requirements.txt
  deploy/svg_generator/svg_generator.py
  deploy/update_server/requirements.txt
  deploy/updater/requirements.txt
  deploy/updater/updater.py
  deploy/weather/requirements.txt
  deploy/weather/weather.py
  deploy/web_server/requirements.txt
  deploy/web_server/web_server.py
  deploy/websocket_server/requirements.txt
Labels: критично, сервер

#291 Сервер: Оновлення бібліотеки
  .github/workflows/deploy_watchdog.yml
  .github/workflows/deploy_websockets.yml
  .github/workflows/deploy_websockets_dev.yml
  deploy/redeploy_websocket_server_dev.sh
  deploy/websocket_server/requirements.txt
  deploy/websocket_server/websocket_server.py
  firmware/src/JaamFirmware.cpp
Labels: критично, сервер

#294 Сервер: Дрібні покращення
  .github/workflows/deploy_websockets.yml
  .github/workflows/deploy_websockets_dev.yml
  deploy/nginx/nginx.conf
  deploy/redeploy_websocket_server.sh
  deploy/redeploy_websocket_server_dev.sh
  deploy/web_server/web_server.py
  deploy/websocket_server/websocket_server.py
  firmware/src/JaamFirmware.cpp
Labels: сервер, технічне

#279 Режими дисплею: можливість відключення погоди у режимі "Перемикання"
  firmware/src/JaamFirmware.cpp
  flasher/bins/jaam_beta.bin
Labels: покращення прошивки

#302 Fix: Повернення режиму "Вимкнено" для кнопок
  firmware/src/JaamFirmware.cpp
Labels: проблема прошивки, критично

#304 Fix: повна підтримка кнопки TTP223
  firmware/src/Constants.h
  firmware/src/JaamButton.cpp
  firmware/src/JaamButton.h
  firmware/src/JaamFirmware.cpp
Labels: проблема прошивки, критично, покращення прошивки

#305 Технічне: Винесення налаштувань в окремий файл
  .github/workflows/linters.yml
  firmware/src/Constants.h
  firmware/src/JaamClimateSensor.cpp
  firmware/src/JaamDisplay.cpp
  firmware/src/JaamFirmware.cpp
  firmware/src/JaamHomeAssistant.cpp
  firmware/src/JaamLightSensor.cpp
  firmware/src/JaamSettings.cpp
  firmware/src/JaamSettings.h
  firmware/src/JaamUtils.h
Labels: покращення прошивки, технічне

#307 Технічне: Зміна основного NTP сервера
  firmware/src/JaamSettings.cpp
Labels: покращення прошивки

#309 Технічне: Отимізація списків налаштувань
  .github/workflows/compile.yml
  firmware/src/Constants.h
  firmware/src/JaamDisplay.cpp
  firmware/src/JaamFirmware.cpp
  firmware/src/JaamHomeAssistant.cpp
  firmware/src/JaamHomeAssistant.h
  firmware/src/JaamUtils.h
Labels: покращення прошивки, технічне

#312 Технічне: Рефакторинг маппінгу LEDs
  firmware/platformio.ini
  firmware/src/Constants.h
  firmware/src/JaamFirmware.cpp
  firmware/src/JaamSettings.cpp
  firmware/src/JaamSettings.h
  firmware/src/JaamUtils.h
Labels: покращення прошивки, технічне
