Repository J-A-A-M/ukraine_alarm_map, pull requests merged in 2025-02, with the labels that each got.

#315 Технічне: Перехід на region ID
  firmware/src/Constants.h
  firmware/src/JaamFirmware.cpp
  firmware/src/JaamSettings.cpp
  firmware/src/JaamUtils.h
  updater/src/updater.cpp
Labels: технічне

#310 Сервер: рефакторінг парсерів даних
  .github/workflows/deploy_server.yml
  .github/workflows/deploy_update_server.yml
  .github/workflows/deploy_websockets.yml
  .github/workflows/deploy_websockets_dev.yml
  .github/workflows/linters.yml
  .github/workflows/pytests.yml
  .gitignore
  deploy/alerts/alerts.py
  deploy/alerts_ws/Dockerfile
  deploy/alerts_ws/alerts.py
  deploy/alerts_ws/requirements.txt
  deploy/etryvoga/etryvoga.py
  deploy/svg_generator/svg_generator.py
  deploy/tests/requirements.txt
  deploy/tests/test_unittest_example.py
  deploy/tests/test_update_alerts_historical_v1.py
  deploy/tests/test_update_alerts_websocket_v1.py
  deploy/tests/test_update_alerts_websocket_v2.py
  deploy/tests/test_update_alerts_websocket_v3.py
  deploy/tests/test_update_drones_etryvoga_v1.py
  deploy/tests/test_update_explosions_etryvoga_v1.py
  deploy/tests/test_update_missiles_etryvoga_v1.py
  deploy/tests/test_update_weather_openweathermap_v1.py
  deploy/update_server/update_server.py
  deploy/updater/__init__.py
  deploy/updater/updater.py
  deploy/weather/weather.py
  deploy/web_server/web_server.py
  deploy/websocket_server/websocket_server.py
Labels: сервер, технічне

#318 Технічне: Покращено механізм обробки версії прошивки
  firmware/src/JaamUtils.h
Labels: технічне

#319 Зміна логіки роботи "нічного часу" для звуків
  firmware/src/JaamFirmware.cpp
Labels: покращення прошивки

#320 Нова сумісність: ESP32-S3, ESP32-C3
  .github/workflows/beta_release.yml
  .github/workflows/compile.yml
  .github/workflows/firmware-compile/action.yml
  .github/workflows/release.yml
  .github/workflows/upload-pages/action.yml
  deploy/redeploy_update_server.sh
  deploy/update_server/update_server.py
  deploy/websocket_server/websocket_server.py
  firmware/platformio.ini
  firmware/src/Constants.h
  firmware/src/Definitions.h
  firmware/src/JaamClimateSensor.cpp
  firmware/src/JaamClimateSensor.h
  firmware/src/JaamDisplay.cpp
  firmware/src/JaamDisplay.h
  firmware/src/JaamFirmware.cpp
  firmware/src/JaamHomeAssistant.h
  firmware/src/JaamLightSensor.cpp
  firmware/src/JaamLightSensor.h
  firmware/src/JaamLogs.h
  firmware/src/JaamSettings.cpp
  firmware/src/JaamUtils.h
  flasher/bins/jaam.bootloader.c3.bin
  flasher/bins/jaam.bootloader.s3.bin
  flasher/bins/jaam.partitions.c3.bin
  flasher/bins/jaam.partitions.s3.bin
  flasher/index.html
  flasher/manifest-beta.json
Labels: покращення прошивки
